### ISSUE TITLE
"Unsupported scheme http" when running the example.

### ISSUE THREAD

**Issue by nicolaspernoud** [felipenoris/hyper-reverse-proxy#38]
Hello,

When running the example with the following dependencies : 
```toml
[package]
name = "proxy_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-reverse-proxy = { git = "https://github.com/felipenoris/hyper-reverse-proxy", branch = "master" }
hyper = { version = "0.14.18", features = ["full"] }
tokio = { version = "1.18.2", features = ["full"] }
lazy_static = "1.4.0"
hyper-trust-dns = { version = "0.4.2", features = [
  "rustls-http2",
  "dnssec-ring",
  "dns-over-https-rustls",
  "rustls-webpki",
  "https-only"
] }

```

I get an `̀_error:HyperError(hyper::Error(Connect, Custom { kind: Other, error: "Unsupported scheme http" }))` when proxying to a local http service. It seems to be related to hyper-trust-dns client, but removing the feature `"https-only"` does nothing...
